### ISSUE TITLE
Comment here is probably "ref to 16 bit nop"?

### ISSUE THREAD

**Issue by uf0o** [0xdea/xorpd-solutions#1]
https://github.com/0xdea/xorpd-solutions/blob/3a84172f615533ffbd40124594db6d36baa6260a/0x1e.asm#L117

**Comment by 0xdea** [comment]
I've clarified what I meant in this commit: https://github.com/0xdea/xorpd-solutions/commit/20e9d55fd22c20187b55b46a79d576a6a2202ab9
Thanks for pointing this out.
