### ISSUE TITLE
Maybe incorrect comment about string[0]

### ISSUE THREAD

**Issue by mattgodbolt** [0xdea/xorpd-solutions#2]
In this line:

https://github.com/0xdea/xorpd-solutions/blob/20e9d55fd22c20187b55b46a79d576a6a2202ab9/0x0f.asm#L28

I think string[0] does not get set to `al`, but rather (if `al` is initially zero), then it's left alone? it's `string[0] ^= 0`, unless I'm missing something (which is entirely possible!)

**Comment by 0xdea** [comment]
Indeed, that was a mistake. I've fixed it now, thank you for pointing that out.

**Comment by mattgodbolt** [comment]
Thanks @0xdea :)
